server:
  port: 8989
  servlet:
    context-path: /ms
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms
    username: root
    password: 123456

  redis:
    port: 6379
    host: localhost
    database: 0
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zitai.ms.entity
  configuration:
    map-underscore-to-camel-case: true


